[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "GEJcReVMo4jq8Z7uF5gQkZTEShmsddbs2ohVH9LjKc9c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/ankush/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
